#!/usr/bin/env sh

PORT=${1:-"4000"}

EXISTS=`docker ps | grep muddled 2> /dev/null`

abort() {
  echo "Error $1 ($!)" 1>&2
  exit 1
}

if [ ! -z "$EXISTS" ]; then
	echo "Stopping muddled..."
	docker stop muddled > /dev/null || abort
	echo "Removing muddled container..."
	docker rm muddled > /dev/null || abort
fi

echo "Starting muddled..."

docker run --name muddled --net host -P -d muddled || abort "Running container"

sleep 5

IP=$(docker inspect muddled --format '{{ .NetworkSettings.IPAddress }}')

echo "Muddled started, you can connect at $IP:$PORT"

exit 0
