#!/bin/sh

DOCKER=$(which docker)
DOCKERMACHINE=$(which docker-machine)

IP=`$DOCKERMACHINE ip default`

if [ $? != 0 ]; then
	echo "Docker not running"
	exit 1
fi

EXISTS=`$DOCKER ps | grep muddled`

if [ ! -z "$EXISTS" ]; then
	echo "Stopping muddled..."
	$DOCKER stop muddled > /dev/null
	echo "Removing muddled container..."
	$DOCKER rm muddled > /dev/null
fi

echo "Creating container..."

$DOCKER create --name muddled --net host -P $1

if [ $? != 0 ]; then 
	echo "Unable to create container ($!)"
	exit 1
fi

echo "Starting muddled..."

$DOCKER start muddled > /dev/null

if [ $? != 0 ]; then
	echo "Unable to start muddled ($!)"
	exit 1
fi

echo "Muddled started, you can connect at telnet://$IP/"

exit 0
